- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present
  register: java_install
  ignore_errors: false

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: "JAVA_HOME={{ java_home }}"
    state: present
  when: java_install is succeeded

- name: Source environment variables
  shell: "source /etc/environment"
  args:
    executable: /bin/bash
  when: ansible_env.JAVA_HOME is not defined